title: Your awesome title
author: 杨超俊
email: yangchaojunxs@126.com
description: > # this means to ignore newlines until "baseurl:"
  欢迎来到我的博客

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
